# Generated by Django 5.1.1 on 2024-09-24 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Название курса', max_length=150, verbose_name='Название')),
                ('preview', models.ImageField(blank=True, help_text='Загрузите превью', null=True, upload_to='lms/course/preview', verbose_name='Превью')),
                ('description', models.TextField(blank=True, help_text='Описание курса', null=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Курс',
                'verbose_name_plural': 'Курсы',
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Название урока', max_length=150, verbose_name='Название')),
                ('preview', models.ImageField(blank=True, help_text='Загрузите превью', null=True, upload_to='lms/lesson/preview', verbose_name='Превью')),
                ('description', models.TextField(blank=True, help_text='Описание урока', null=True, verbose_name='Описание')),
                ('links_to_video', models.URLField(blank=True, help_text='Ссылка на видео по уроку', null=True, verbose_name='Ссылка на видео')),
                ('courses', models.ManyToManyField(blank=True, null=True, related_name='lessons', to='lms.course', verbose_name='Курсы')),
            ],
            options={
                'verbose_name': 'Урок',
                'verbose_name_plural': 'Уроки',
            },
        ),
    ]
