# Generated by Django 5.1.1 on 2024-09-24 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='courses',
            field=models.ManyToManyField(related_name='lessons', to='lms.course', verbose_name='Курсы'),
        ),
    ]
